---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "static-files"
  labels:
    nirmata.io/deployment.name: "static-files"
    nirmata.io/service.name: "static-files"
    nirmata.io/type: "app"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/service.name: "static-files"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "static-files"
        nirmata.io/service.name: "static-files"
        nirmata.io/type: "app"
    spec:
      serviceAccountName: "staticfiles-service"
      automountServiceAccountToken: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      schedulerName: "default-scheduler"
      priorityClassName: "nirmata-app-lower"
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: registry-v2.nirmata.io
      - name: ghcr.io
      containers:
      - name: "static-files"
        image: "ghcr.io/nirmata/nirmata-static-files:4.13.0-19.g595061e"
        command:
        - "/run.sh"
        args: []
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          protocol: "TCP"
        env:
        - name: "nirmata.environment.name"
          valueFrom:
            fieldRef:
              apiVersion: "v1"
              fieldPath: "metadata.namespace"
        - name: "nirmata.product.version"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "productVersion"
        - name: "IMAGE_REGISTRY"
        - name: "IMAGE_REGISTRY_USERNAME"
        - name: "IMAGE_REGISTRY_PASSWORD"
        - name: "NIRMATA_URL"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "nirmata.url"
        - name: "HTTP_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTP_PROXY"
        - name: "HTTPS_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTPS_PROXY"
        - name: "NO_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "NO_PROXY"
        - name: "http_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "http_proxy"
        - name: "https_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "https_proxy"
        - name: "no_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "no_proxy"
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: 8080
        resources:
          limits:
            memory: "32Mi"
          requests:
            memory: "32Mi"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        supplementalGroups: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - namespaces: []
            labelSelector:
              matchLabels: {}
              matchExpressions:
              - key: "nirmata.io/deployment.name"
                operator: "In"
                values:
                - "static-files"
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
