---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "haproxy"
  labels:
    nirmata.io/deployment.name: "haproxy"
    nirmata.io/service.name: "haproxy"
    nirmata.io/type: "app"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      nirmata.io/deployment.name: "haproxy"
      nirmata.io/service.name: "haproxy"
      nirmata.io/type: "app"
    matchExpressions: []
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations: {}
      labels:
        nirmata.io/deployment.name: "haproxy"
        nirmata.io/service.name: "haproxy"
        nirmata.io/type: "app"
    spec:
      serviceAccountName: "haproxy-service"
      automountServiceAccountToken: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      schedulerName: "default-scheduler"
      priorityClassName: "nirmata-app-critical"
      dnsPolicy: "ClusterFirst"
      volumes:
      - name: "cert"
        secret:
          secretName: "server-certificate"
          defaultMode: 420
      - name: haproxy-config-volume
        configMap:
          name: haproxy-nirmata-config
          defaultMode: 0777
      imagePullSecrets:
      - name: registry-v2.nirmata.io
      - name: ghcr.io
      containers:
      - name: "haproxy"
        image: "ghcr.io/nirmata/haproxy:4.13.0-14.ga350ede"
        command: []
        args: []
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: "File"
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: "https"
          containerPort: 8443
          protocol: "TCP"
        - name: "stats"
          containerPort: 1936
          protocol: "TCP"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "service.logs.level"
          value: "warn"
        - name: "HTTP_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTP_PROXY"
        - name: "HTTPS_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "HTTPS_PROXY"
        - name: "NO_PROXY"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "NO_PROXY"
        - name: "http_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "http_proxy"
        - name: "https_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "https_proxy"
        - name: "no_proxy"
          valueFrom:
            configMapKeyRef:
              name: "nirmata-config"
              key: "no_proxy"
        volumeMounts:
        - name: "cert"
          mountPath: "/mnt/secrets"
        - mountPath: /tmp/haproxy.cfg
          subPath: haproxy.cfg
          name: haproxy-config-volume
          readOnly: false
        livenessProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: 8443
        readinessProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/security/status"
            port: 8443
            scheme: "HTTPS"
        resources:
          limits:
            memory: "100Mi"
          requests:
            memory: "100Mi"
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        supplementalGroups: []
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - namespaces: []
            labelSelector:
              matchLabels: {}
              matchExpressions:
              - key: "nirmata.io/deployment.name"
                operator: "In"
                values:
                - "haproxy"
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 20
