# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haproxy-deployment-restart
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: haproxy-deployment-restart
subjects:
  - kind: ServiceAccount
    name: haproxy-deployment-restart
    namespace: prod
