---
apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "orchestrator-pdb"
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "orchestrator"
    matchExpressions: []
