---
apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "client-gateway-pdb"
  labels: {}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      nirmata.io/service.name: "client-gateway"
    matchExpressions: []
