apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: environments-helm-runner
subjects:
- kind: ServiceAccount
  name: environments-service
  apiGroup: ""
- kind: ServiceAccount
  name: environments-processor-service
  apiGroup: ""
roleRef:
  kind: Role
  name: helm-runner
  apiGroup: rbac.authorization.k8s.io
