---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tunnel-wss"
  labels:
    nirmata.io/service.name: "tunnel"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "tunnel"
  ports:
  - name: "wss"
    port: 443
    protocol: "TCP"
    targetPort: 8443
