---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "zookeeper-dd-hl"
  labels:
    app: "zk"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    app: "zk"
  ports:
  - name: "client"
    port: 2181
    protocol: "TCP"
    targetPort: 2181
