apiVersion: "v1"
kind: "Service"
metadata:
  name: "policies"
  labels:
    nirmata.io/service.name: "policies"
spec:
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "policies"
  ports:
  - name: "https"
    port: 443 
    protocol: "TCP"
    targetPort: 8443
