apiVersion: v1
kind: Service
metadata:
  labels:
    nirmata.io/service.name: environments-processor
  name: environments-processor
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    nirmata.io/service.name: environments-processor
  type: ClusterIP
