---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "config"
  labels:
    nirmata.io/service.name: "config"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "config"
  ports:
  - name: "https"
    port: 443
    protocol: "TCP"
    targetPort: 8443
