apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    nirmata.io/service.name: catalog
  name: catalog
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    nirmata.io/service.name: catalog
  sessionAffinity: None
  type: ClusterIP