---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kafka"
  labels:
    app: "kafka"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    app: "kafka"
  ports:
  - name: "broker"
    port: 9092
    protocol: "TCP"
    targetPort: 9092
