---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tunnel"
  labels:
    nirmata.io/service.name: "tunnel"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "tunnel"
  ports:
  - name: "api"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
