---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kafka-controller"
  labels:
    app: "kafka-controller"
spec:
  clusterIP: "None"
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    app: "kafka-controller"
  ports:
  - name: "controller"
    port: 9093
    protocol: "TCP"
    targetPort: 9093
