---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "static-files"
  labels:
    nirmata.io/service.name: "static-files"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  sessionAffinity: "None"
  type: "ClusterIP"
  selector:
    nirmata.io/service.name: "static-files"
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
